blank_issues_enabled: false
contact_links:
    - name: Suggestions
      url: https://github.com/lezzthanthree/SIFAS-Dialogue-Sandbox/discussions/categories/ideas
      about: Any suggestions or feature requests go here