name: Bug Report
description: Report if a bug has occured.
body:
  - type: textarea 
    attributes:
      label: The problem
      description: Provide details of the bug, how to get the bug, etc.
    validations:
      required: true
  - type: textarea 
    attributes:
      label: Screenshot
      description: Add a screenshot of the bug
      placeholder: Drag and drop the screenshots into this box.
    validations:
      required: true