name: Sprite Issue
description: Report if a sprite is not rendering properly.
body:
  - type: dropdown
    attributes:
      label: Character
      description: Whose character has incorrect rendering?
      options:
        - Ai
        - Ayumu
        - Chika
        - Dia
        - Eli
        - Emma
        - Hanamaru
        - Hanayo
        - Honoka
        - Kanan
        - Kanata
        - Karin
        - Kasumi
        - Kotori
        - Lanzhu
        - Maki
        - Mari
        - Mia
        - Nico
        - Nozomi
        - Riko
        - Rin
        - Rina
        - Rina_board
        - Ruby
        - Setsuna
        - Shioriko
        - Shizuku
        - Umi
        - Yoshiko
        - You
    validations:
      required: true
  - type: textarea 
    attributes:
      label: Details/Screenshot
      description: Add a screenshot of the sprite or provide screenshots.
      placeholder: You can drag and drop screenshots into this box.
    validations:
      required: true
  - type: input
    attributes:
      label: Eye Expression.
      description: The value of the eye expression used.
    validations:
      required: true
  - type: input
    attributes:
      label: Mouth Expression
      description: The value of the mouth expression used.
    validations:
      required: true